### ISSUE TITLE
Graph visualization is not working properly with an adapted config (Temperature data not available)

### ISSUE THREAD

**Issue by maurosbicego** [Sailowtech/Sailowtech-CTD#14]
After adapting the config to a new set of sensors, the visualization in the web interface was not working properly. Data for temperature was not visible in our tests.

Example of missing temperature data:
![Image](https://github.com/user-attachments/assets/9dd04041-d044-4459-936c-b0c182976e18)

(The data was measured correctly and is stored in the DB)

Used Config:

```
device: Sailowtech CTD
sensors:
  dissolved-oxygen:
    name: "Dissolved Oxygen 1"
    address: 0x61
    sensor-type: "ATLAS_EZO_DO"
    min-delay: 1.05
  dissolved-oxygen-2:
    name: "Dissolved Oxygen 2"
    address: 0x62
    sensor-type: "ATLAS_EZO_DO"
    min-delay: 1.05
  conductivity:
    name: "Conductivity Probe"
    address: 0x64
    sensor-type: "ATLAS_EZO_CONDUCTIVITY"
    min-delay: 1.05
  temperature-do:
    name: "Temperature (DO Sensor)"
    address: 0x67
    sensor-type: "ATLAS_EZO_TEMP"
    min-delay: 1.05
  depth:
    name: "Depth Sensor"
    address: 0x76
    sensor-type: "BLUEROBOTICS_BAR30_DEPTH"
    min-delay: 1.05
mock: false
```

Reporter: @benedictelunven
